spring:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  uploadDir: ./uploads
  publicBaseUrl: http://localhost:8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
